services:
  # --- DB User ---
  postgres-user:
    image: postgres:15-alpine
    container_name: storm-postgres-user
    environment:
      POSTGRES_USER: storm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storm_user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storm -d storm_user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- DB Message ---
  postgres-chat:
    image: postgres:15-alpine
    container_name: storm-postgres-chat
    environment:
      POSTGRES_USER: storm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storm_message_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_message_data:/var/lib/postgresql/data

  # --- Message Broker ---
  nats:
    image: nats:latest
    container_name: storm-nats
    ports:
      - "4222:4222" # Port Client
      - "8222:8222" # Dashboard Web 
    command: "-js -m 8222" 

  # --- Cache ---
  redis:
    image: redis:alpine
    container_name: storm-redis
    ports:
      - "6379:6379"

  # --- Object Storage ---
  minio:
    image: minio/minio
    container_name: storm-minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_user_data:
  postgres_message_data:
  minio_data: