apiVersion: v1
kind: ConfigMap
metadata:
  name: storm-config
  namespace: storm
data:
  # NATS — broker de messages
  NATS_URL: "nats://nats:4222"

  # Redis — cache / sessions
  REDIS_ADDR: "redis:6379"

  # MinIO — stockage objet local
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "media"

  # URLs inter-services
  USER_SERVICE_URL: "http://user-service:3000"

  # Bases de données PostgreSQL
  DB_HOST_USER: "postgres-user"
  DB_HOST_MESSAGE: "postgres-message"
  DB_PORT: "5432"