apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: storm
type: Opaque
stringData:
  POSTGRES_USER: storm
  POSTGRES_PASSWORD: password

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: storm
type: Opaque
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: storm
type: Opaque
stringData:
  # Générer en prod : openssl rand -hex 32
  JWT_SECRET: "storm-secret-key-change-in-production"
